### ISSUE TITLE
BUG: verify new email link throws 500 internal server error

### ISSUE THREAD

**Issue by crydotsnake** [neos/Neos.IdNeosIo#26]
I tried to change my email address to id.neos.io. This has also worked so far. However, when I click on the verification link of my new email address, I get a `500 Internal Server Error` as a response.

I tried it with my neos.io email, and even with my private email. Both didnt work.

[error-log.txt](https://github.com/neos/Neos.IdNeosIo/files/12866326/error-log.txt)

**Comment by bwaidelich** [comment]
@crydotsnake you should have access to the error logs, did you check those already?

**Comment by bwaidelich** [comment]
So that seems to be a (new?) limitation of Atlassian Crowd

**Comment by bwaidelich** [comment]
See https://jira.atlassian.com/browse/CWD-5792

**Comment by kdambekalns** [comment]
The fix _should_ be:

> I confirm that setting up JVM parameter `-Dcrowd.email.change.by.external.apps=true` is a working solution

So, somone at netlogix can hopefully fix this…

**Comment by kdambekalns** [comment]
@crydotsnake Can you try again, to see if it's fixed?
